activation:
  beginner: {days: 7, hours: 15}
  confirmed: {days: 12, hours: 25}
  second: {days: 20, hours: 80}
confirmed_threshold_diamants: 150000
beginner_bonuses:
  days_window: 90
  milestones:
    - {min: 75000,  max: 149999,  bonus: 500,  code: B1}
    - {min: 150000, max: 499999,  bonus: 1088, code: B2}
    - {min: 500000, max: 2000000, bonus: 3000, code: B3}
